### ISSUE TITLE
rename package

### ISSUE THREAD

**Issue by adam-hanna** [c3systems/c3-sdk-go#1]
go-c3-sdk -> c3-go-sdk

**Comment by miguelmota** [comment]
personally i think it's strange to have the language in the middle

`<language>-<project>-<library>` (e.g ipfs,libp2p)

`<project>-<library>-<library>` (e.g. aws)

**Comment by adam-hanna** [comment]
agreed. let's move it to the last thing: `<project>-<library>-<language>`
